spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentmanager?setUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: 1234



mybatis:
  type-aliases-package: com.wdd.studentmanager.domain
  mapper-locations: classpath:mapper/*.xml
#加载映射文件
